# Generated by Django 3.2.8 on 2021-10-21 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('descripcion', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Estadistica',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('puntaje', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.SmallIntegerField(default=0)),
                ('cargo', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('contraseña', models.CharField(max_length=50)),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=250)),
                ('pregunta', models.CharField(choices=[(1, 'Escrita'), (2, 'Verdadero_Falso'), (3, 'Opcion_multiple')], default=1, max_length=1)),
                ('respuesta', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.SmallIntegerField(default=0)),
                ('cargo', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('contraseña', models.CharField(max_length=50)),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('num_preguntas', models.PositiveIntegerField()),
                ('estado', models.BooleanField(default=True)),
                ('estadisticas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Crystal_Clear_App.estadistica')),
                ('preguntas', models.ManyToManyField(to='Crystal_Clear_App.Pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=250)),
                ('Creditos', models.PositiveSmallIntegerField()),
                ('estado', models.BooleanField(default=True)),
                ('estudiantes', models.ManyToManyField(to='Crystal_Clear_App.Estudiante')),
                ('examenes', models.ManyToManyField(to='Crystal_Clear_App.Examen')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Crystal_Clear_App.profesor')),
            ],
        ),
    ]
