# Generated by Django 3.2.8 on 2021-11-09 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crystal_Clear_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='estadisticas',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Crystal_Clear_App.estadistica'),
        ),
    ]
