# Generated by Django 3.2.8 on 2021-10-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crystal_Clear_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='examenes',
            field=models.ManyToManyField(blank=True, to='Crystal_Clear_App.Examen'),
        ),
    ]
