# Generated by Django 3.2.8 on 2021-11-09 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crystal_Clear_App', '0002_alter_examen_estadisticas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examen',
            name='estadisticas',
        ),
    ]
