# Generated by Django 3.2.8 on 2021-11-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crystal_Clear_App', '0003_alter_clase_estudiantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
