# Generated by Django 3.2.8 on 2021-11-10 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crystal_Clear_App', '0003_remove_examen_estadisticas'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreguntaVedaderoFalso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.PositiveIntegerField()),
                ('pregunta', models.CharField(max_length=600)),
                ('opcion1', models.CharField(max_length=200)),
                ('opcion2', models.CharField(max_length=200)),
                ('opcion3', models.CharField(max_length=200)),
                ('opcion4', models.CharField(max_length=200)),
                ('answer', models.CharField(choices=[('Option1', 'Option1'), ('Option2', 'Option2'), ('Option3', 'Option3'), ('Option4', 'Option4')], max_length=200)),
            ],
        ),
    ]
