# Generated by Django 3.2.8 on 2021-11-02 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crystal_Clear_App', '0004_alter_clase_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clase',
            old_name='Creditos',
            new_name='creditos',
        ),
    ]
