# Generated by Django 3.2.8 on 2021-11-03 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crystal_Clear_App', '0005_rename_creditos_clase_creditos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='cargo',
        ),
    ]
